### Register Mod
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "mod",
  "email": "mod@gokalpcelik.com",
  "password": "testPassword",
  "role": ["mod", "user"]
}

### Register Admin
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@gokalpcelik.com",
  "password": "testPassword",
  "role": ["admin","mod", "user"]
}

### Register User
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "user",
  "email": "user@gokalpcelik.com",
  "password": "testPassword",
  "role": ["user"]
}

### Sigin Mod
POST localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "mod",
  "password": "testPassword"
}


### Sigin Admin
POST localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "testPassword"
}


### Sigin User
POST localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "user",
  "password": "testPassword"
}

### test-all
GET localhost:8080/api/test/all

### test-user
GET localhost:8080/api/test/user

### test-mod
GET localhost:8080/api/test/mod

### test-admin
GET localhost:8080/api/test/admin

### sign-in
POST localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "mod",
  "password": "testPassword"
}

### sign-out
POST localhost:8080/api/auth/signout
Content-Type: application/json

